name: 'ROS 2 launchfile test'
author: 'Guillem Torrente (tmguillem)'
description: 'Github Action that executes a ROS 2 launchfile and verifies that specific topics are being published'
branding:
  icon: 'activity'  
  color: 'black'
inputs:
  package:
    description: 'Package name where the launchfile is located. E.g.: my_package'
    required: true

  launchfile:
    description: 'Name of the launchfile within the package. E.g.: my_launch_file.py'
    required: true

  ros_args:
    description: 'Chain of ros arguments for launchfile. E.g.: my_bool_arg:=false'
    required: false
    default: ''

  listen_topics:
    description: 'List of topics that will be verified. E.g.: /my_topic_1 /my_node/another_topic_2'
    required: true

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.package }}
    - ${{ inputs.launchfile }}
    - ${{ inputs.ros_args }}
    - ${{ inputs.listen_topics }}
